version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    command: serve -s build
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
